// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyykwityaigxofimbvqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5eWt3aXR5YWlneG9maW1idnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzg5NTMsImV4cCI6MjA3MDc1NDk1M30.utg39busN3mem-xfJqY8BgVM0Ltv8ZfYP2Fv3KAs2xA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});