// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zctjukybradliycnoaff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjdGp1a3licmFkbGl5Y25vYWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzEwNTAsImV4cCI6MjA2NDU0NzA1MH0.hcJf6ggd6gosN4ruwmhG1d8RcNeGiE6Bynu3WslYklY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);